### local endpoint
POST http://localhost:8787 HTTP/1.1
content-type: application/json

{
    "messages": [
        {
            "role": "user",
            "content": "Generate a python function that adds two numbers."
        }
    ],
    "max_tokens": 100,
    "temperature": 0.1
}

### prod endpoint
POST https://llm.boardflare.com HTTP/1.1
content-type: application/json

{
    "model": "mistral-large-2411",
    "messages": [
        {
            "role": "user",
            "content": "What is the capital of France?"
        }
    ],
    "max_tokens": 250,
    "temperature": 0
}

