name: Static preview deploy

on:
    push:
        branches: [ preview ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name 'boardflareaddins' -d 'python/preview' -s './app' --overwrite --sas-token '${{ secrets.CONTAINER_SAS_TOKEN }}'